### ISSUE TITLE
A unit test is using Redis?

### ISSUE THREAD

**Issue by msabramo** [hipache/hipache#198] opened 2015-01-05 04:44 UTC
It appears that one or more unit tests are using Redis? I would expect only functional tests to use Redis and unit tests would either be independent of external data storage or would use mocks?

```
$ gulp test:unit
[15:40:01] Using gulpfile ~/dev/git-repos/hipache/gulpfile.js
[15:40:01] Starting 'test:unit'...


  Config
    Configuration loading
      ✓ From string
      ✓ From buffer
      ✓ From object
    Broken...
      ✓ ... broken json
      ✓ ... https missing key file
      ✓ ... https missing cert file
      ✓ ... https missing ca file
      ✓ ... https missing key
      ✓ ... https missing cert
    Running as root
      ✓ Not running root test as we are not root...

  Driver factory
    #existing-drivers
      ✓ redis: (67ms)
      ✓ memcached:// (127ms)
      ✓ etcd: (643ms)
      ✓ etcds://
      ✓ redis:///ß∞
      1) redis:///ß∞
      ✓ redis://,redis://
    #erroring-on-bogus-urls
      ✓ "nopassaran://" (unregistered) should emit error
      ✓ "bogus" (no scheme) should emit error
      ✓ drivertpl:// (which is broken) should emit error

  Logger
    #creation
      ✓ err with undefined path
      ✓ err trying to open a folder
      ✓ err trying to open file in nested non existent directory
      ✓ err trying to open file with no permissions
    #trying to log in the wrong state
      ✓ stream has been closed
    #legit logging
      ✓ empty data
      ✓ legit data

  Lru
    #dumb lru
      ✓ Get, set, del
    #real lru
      ✓ Simple get, set, del
    #real lru limits
      ✓ Reaching the number of objects limits
      ✓ Reaching the ttl (52ms)


  30 passing (926ms)
  1 failing

  1) Driver factory #existing-drivers redis:///ß∞:
     Uncaught
  DriverError: Error: Redis connection to 127.0.0.1:6379 failed - connect ECONNREFUSED
      at null.<anonymous> (/Users/marca/dev/git-repos/hipache/lib/drivers/redis.js:38:35)
      at RedisClient.emit (events.js:95:17)
      at RedisClient.on_error (/Users/marca/dev/git-repos/hipache/node_modules/redis/index.js:185:10)
      at Socket.<anonymous> (/Users/marca/dev/git-repos/hipache/node_modules/redis/index.js:95:14)
      at Socket.emit (events.js:95:17)
      at net.js:441:14
      at process._tickCallback (node.js:442:13)



[15:40:02] 'test:unit' errored after 1.15 s
[15:40:02] Error in plugin 'gulp-mocha'
1 test failed.
```

**Comment by msabramo** [comment] 2015-01-05 05:35
See https://github.com/hipache/hipache/pull/199 for a possible solution...

**Comment by dmp42** [comment] 2015-01-05 08:23
See my comment over there.
This points to a bug in either the redis driver or the test itself - either way that should be fixed, not removed.

Bottom-line: this should fail connecting to redis and be caught silently, like it does for the other tests.

(and, ah, mocks are evil :))

**Comment by willdurand** [comment] 2015-01-05 09:18
This test does not fail on my side, so I think it is not worth removing it.

**Comment by dmp42** [comment] 2015-01-06 06:18
Ok, let's get to the bottom of this - since I can't reproduce.

Can you please copy the output of these:

```
node --version
redis-server --version
cd your_hipache_checkout; npm list | grep redis
ps aux | grep redis
```

**Comment by msabramo** [comment] 2015-01-06 07:08
```
[marca@marca-mac2 hipache]$ node --version
v0.10.35
[marca@marca-mac2 hipache]$ redis-server --version
Redis server v=2.8.17 sha=00000000:0 malloc=libc bits=64 build=32eb139b4f2b63
[marca@marca-mac2 hipache]$ npm list | grep redis
├── redis@0.10.3
npm ERR! extraneous: npm@1.4.10 /Users/marca/dev/git-repos/hipache/node_modules/npm
npm ERR! extraneous: inherits@2.0.1 /Users/marca/dev/git-repos/hipache/node_modules/npm/node_modules/inherits
npm ERR! extraneous: normalize-package-data@1.0.3 /Users/marca/dev/git-repos/hipache/node_modules/npm/node_modules/normalize-package-data
npm ERR! not ok code 0
[marca@marca-mac2 hipache]$ ps aux | grep redis
marca           98256   0.0  0.1  2506948  14564 s002  T     4:21PM   0:06.19 vim lib/drivers/redis.js +38
marca           24616   0.0  0.0  2440976    528 s002  R+   11:08PM   0:00.00 grep redis
```

**Comment by msabramo** [comment] 2015-01-06 07:10
Hmmm, those npm ERR! look concerning. I'm going to try blowing away `node_modules` and doing `npm install` again.

**Comment by msabramo** [comment] 2015-01-06 07:12
```
1 test failed.
[marca@marca-mac2 hipache]$ npm list | grep redis
├── redis@0.10.3
```

Also upgraded redis-server.

```
[marca@marca-mac2 hipache]$ redis-server --version
Redis server v=2.8.19 sha=00000000:0 malloc=libc bits=64 build=f9a9a1252a078d97
```

Tests still failing:

```
[marca@marca-mac2 hipache]$ gulp test:unit
[23:11:47] Using gulpfile ~/dev/git-repos/hipache/gulpfile.js
[23:11:47] Starting 'test:unit'...


  Config
    Configuration loading
      ✓ From string
      ✓ From buffer
      ✓ From object
    Broken...
      ✓ ... broken json
      ✓ ... https missing key file
      ✓ ... https missing cert file
      ✓ ... https missing ca file
      ✓ ... https missing key
      ✓ ... https missing cert
    Running as root
      ✓ Not running root test as we are not root...

  Driver factory
    #existing-drivers
      ✓ redis:
      ✓ memcached://
      ✓ etcd: (97ms)
      ✓ etcds://
      ✓ redis:///ß∞
      1) redis:///ß∞
      ✓ redis://,redis://
    #erroring-on-bogus-urls
      ✓ "nopassaran://" (unregistered) should emit error
      ✓ "bogus" (no scheme) should emit error
      ✓ drivertpl:// (which is broken) should emit error

  Logger
    #creation
      ✓ err with undefined path
      ✓ err trying to open a folder
      ✓ err trying to open file in nested non existent directory
      ✓ err trying to open file with no permissions
    #trying to log in the wrong state
      ✓ stream has been closed
    #legit logging
      ✓ empty data
      ✓ legit data

  Lru
    #dumb lru
      ✓ Get, set, del
    #real lru
      ✓ Simple get, set, del
    #real lru limits
      ✓ Reaching the number of objects limits
      ✓ Reaching the ttl (52ms)


  30 passing (228ms)
  1 failing

  1) Driver factory #existing-drivers redis:///ß∞:
     Uncaught
  DriverError: Error: Redis connection to 127.0.0.1:6379 failed - connect ECONNREFUSED
      at null.<anonymous> (/Users/marca/dev/git-repos/hipache/lib/drivers/redis.js:38:35)
      at RedisClient.emit (events.js:95:17)
      at RedisClient.on_error (/Users/marca/dev/git-repos/hipache/node_modules/redis/index.js:185:10)
      at Socket.<anonymous> (/Users/marca/dev/git-repos/hipache/node_modules/redis/index.js:95:14)
      at Socket.emit (events.js:95:17)
      at net.js:441:14
      at process._tickCallback (node.js:442:13)



[23:11:47] 'test:unit' errored after 291 ms
[23:11:47] Error in plugin 'gulp-mocha'
1 test failed.
```

**Comment by msabramo** [comment] 2015-01-06 07:14
On my Ubuntu 14.04 system where all the tests pass, I have:

```
vagrant@vagrant-ubuntu-trusty-64:~/hipache$ node --version
v0.10.26
vagrant@vagrant-ubuntu-trusty-64:~/hipache$ redis-server --version
Redis server v=2.8.4 sha=00000000:0 malloc=jemalloc-3.4.1 bits=64 build=a44a05d76f06a5d9
vagrant@vagrant-ubuntu-trusty-64:~/hipache$ npm list | grep redis
├── redis@0.10.3
vagrant@vagrant-ubuntu-trusty-64:~/hipache$ ps aux | grep redis
redis     1176  0.1  0.7  36996  7296 ?        Ssl  06:20   0:03 /usr/bin/redis-server 127.0.0.1:6379
vagrant   7567  0.0  0.0  10468   916 pts/1    S+   07:14   0:00 grep --color=auto redis
```

**Comment by msabramo** [comment] 2015-01-06 07:17
Ah ha. I noticed that my Ubuntu 14.04 had a redis-server running and my OS X did not. I did:

```
[marca@marca-mac2 hipache]$ launchctl unload ~/Library/LaunchAgents/homebrew.mxcl.redis.plist
[marca@marca-mac2 hipache]$ launchctl load ~/Library/LaunchAgents/homebrew.mxcl.redis.plist
[marca@marca-mac2 hipache]$ pgrep -fl redis
25424 /usr/local/opt/redis/bin/redis-server 127.0.0.1:6379
98256 vim lib/drivers/redis.js +38
```

and now the tests pass.

That seems wrong though that the tests would require a redis server to already be running...? They should be starting their own redis server, no?

**Comment by msabramo** [comment] 2015-01-06 07:18
Just to add extra proof, I stopped redis-server on the Ubuntu box and then I get the same failure there:

```
vagrant@vagrant-ubuntu-trusty-64:~/hipache$ sudo /etc/init.d/redis-server stop
Stopping redis-server: redis-server.
vagrant@vagrant-ubuntu-trusty-64:~/hipache$ gulp test:unit
[07:17:36] Using gulpfile ~/hipache/gulpfile.js
[07:17:36] Starting 'test:unit'...


  Config
    Configuration loading
      ✓ From string
      ✓ From buffer
      ✓ From object
    Broken...
      ✓ ... broken json
      ✓ ... https missing key file
      ✓ ... https missing cert file
      ✓ ... https missing ca file
      ✓ ... https missing key
      ✓ ... https missing cert
    Running as root
      ✓ Not running root test as we are not root...

  Driver factory
    #existing-drivers
      ✓ redis:
      ✓ memcached://
      ✓ etcd: (95ms)
      ✓ etcds://
      ✓ redis:///ß∞
      1) redis:///ß∞
      ✓ redis://,redis://
    #erroring-on-bogus-urls
      ✓ "nopassaran://" (unregistered) should emit error
      ✓ "bogus" (no scheme) should emit error
      ✓ drivertpl:// (which is broken) should emit error

  Logger
    #creation
      ✓ err with undefined path
      ✓ err trying to open a folder
      ✓ err trying to open file in nested non existent directory
      ✓ err trying to open file with no permissions
    #trying to log in the wrong state
      ✓ stream has been closed
    #legit logging
      ✓ empty data
      ✓ legit data

  Lru
    #dumb lru
      ✓ Get, set, del
    #real lru
      ✓ Simple get, set, del
    #real lru limits
      ✓ Reaching the number of objects limits
      ✓ Reaching the ttl (53ms)


  30 passing (258ms)
  1 failing

  1) Driver factory #existing-drivers redis:///ß∞:
     Uncaught
  DriverError: Error: Redis connection to 127.0.0.1:6379 failed - connect ECONNREFUSED
      at null.<anonymous> (/home/vagrant/hipache/lib/drivers/redis.js:38:35)
      at RedisClient.EventEmitter.emit (events.js:95:17)
      at RedisClient.on_error (/home/vagrant/hipache/node_modules/redis/index.js:185:10)
      at Socket.<anonymous> (/home/vagrant/hipache/node_modules/redis/index.js:95:14)
      at Socket.EventEmitter.emit (events.js:95:17)
      at net.js:440:14
      at process._tickCallback (node.js:415:13)



[07:17:37] 'test:unit' errored after 323 ms
[07:17:37] Error in plugin 'gulp-mocha'
1 test failed.
```

**Comment by msabramo** [comment] 2015-01-06 18:00
@dmp42: Could it be because it seems an error is emitted **twice**?

```
[marca@marca-mac2 hipache]$ gulp test:unit:factory
[16:51:46] Using gulpfile ~/dev/git-repos/hipache/gulpfile.js
[16:51:46] Starting 'test:unit:factory'...


  Driver factory
    #existing-drivers
      ** at the bottom of Redis() function
      ✓ redis:///ß∞
      ** Emitting redis error; this = [object Object]; this.ERROR = error; err = "Error: Redis connection to 127.0.0.1:6379 failed - connect ECONNREFUSED"
      ** destructor **
      ** destructor: cleared monitorPoller; doing client.end() **
      ** destructor: did client.end() **
      ** done with destructor **
      ** Emitting redis error; this = [object Object]; this.ERROR = error; err = "Error: Redis connection to 127.0.0.1:6379 failed - connect ECONNREFUSED"
      1) redis:///ß∞


  1 passing (27ms)
  1 failing

  1) Driver factory #existing-drivers redis:///ß∞:
     Uncaught
  DriverError: Error: Redis connection to 127.0.0.1:6379 failed - connect ECONNREFUSED
      at null.<anonymous> (/Users/marca/dev/git-repos/hipache/lib/drivers/redis.js:39:35)
      at RedisClient.emit (events.js:95:17)
      at RedisClient.on_error (/Users/marca/dev/git-repos/hipache/node_modules/redis/index.js:185:10)
      at Socket.<anonymous> (/Users/marca/dev/git-repos/hipache/node_modules/redis/index.js:95:14)
      at Socket.emit (events.js:95:17)
      at net.js:441:14
      at process._tickCallback (node.js:442:13)



[16:51:46] 'test:unit:factory' errored after 78 ms
[16:51:46] Error in plugin 'gulp-mocha'
1 test failed.
```

**Comment by msabramo** [comment] 2015-01-06 18:01
So now the question is why do the tests rely on having a redis server running and how can that be fixed?

**Comment by dmp42** [comment] 2015-01-06 18:25
Bottom-line: they don't rely on a running redis server. They should run without (and they do for me).

I'll try on a random ubuntu box from scratch and see what goes.

**Comment by willdurand** [comment] 2015-01-06 21:25
Unit tests don't rely on a running redis server on my side as well :/

**Comment by dmp42** [comment] 2015-01-07 00:03
Fixed

**Closed by dmp42** 2015-01-07 00:03 UTC
